language: generic

os:
  - linux
  - osx

matrix:
  exclude:
    # Skip extra Linux configurations that the "os:" entry adds.
    - os: linux
  include:
    # Clang
    - os: linux
      env: COMPILER_NAME=clang CC=clang CXX=clang++ DEPLOY_DOCS=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 doxygen

    # GCC 5
    - os: linux
      env: COMPILER_NAME=g++ CC=gcc-5 CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    # GCC 7
    - os: linux
      env: COMPILER_NAME=g++ CC=gcc-7 CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

install:
  - if [[ "$DEPLOY_DOCS" == "1" ]]; then
      pip install --user Sphinx;
    fi

script:
  - git clone https://github.com/KhronosGroup/SPIRV-Headers
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget -q https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip;
      unzip SPIRV-Tools-master-linux-RelWithDebInfo.zip -d SPIRV-Tools;
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      wget -q https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-osx-RelWithDebInfo.zip;
      unzip SPIRV-Tools-master-osx-RelWithDebInfo.zip -d SPIRV-Tools;
    fi
  - cmake . -DSPIRV_INCLUDE_DIR=$PWD/SPIRV-Headers/include
            -DSPIRV_TOOLS_INCLUDE_DIR=$PWD/SPIRV-Tools/include
            -DSPIRV_TOOLS_LIBRARY_DIR=$PWD/SPIRV-Tools/lib
  - make -j 2
  - ctest . --output-on-failure

after_success:
  - if [[ "$DEPLOY_DOCS" == "1" ]]; then
      mkdir build-docs;
      touch build-docs/.nojekyll;
      pip install --user m2r;
      sphinx-build -b html -c $PWD/docs/ $PWD/docs/sphinx build-docs;
      (cat docs/Doxyfile; echo "OUTPUT_DIRECTORY=build-docs/api"; echo "HTML_OUTPUT=.") | doxygen -;
    fi

deploy:
  provider: pages
  repo: talvos/talvos.github.io
  target-branch: master
  local-dir: build-docs
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    condition: $DEPLOY_DOCS == 1
